#!/bin/bash

TODAY=$(TZ=":US/Eastern" date)
echo $TODAY >> /home/ec2-user/log.txt
~/.nvm/versions/node/v13.10.1/bin/node /home/ec2-user/oneoff-scripts/cron/index.js >> /home/ec2-user/log.txt
echo >> /home/ec2-user/log.txt
rm -rf /home/ec2-user/oneoff-scripts/cron/path
rm -rf /home/ec2-user/path
